version: '3'

volumes:
  data: {}

services:
  sapozhnikabot: &sapozhnikabot
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: sapozhnikabot
    env_file:
      - ./.envs/.production
    command: python main.py
    restart: always
    volumes:
      - data:/data
